// ============================================================
// DEPRECATED — DO NOT EDIT THIS FILE
// ============================================================
// This is the original Next.js source. It is NOT used by the
// live app. All changes must go to the Vite app instead:
//
//   artifacts/calculatetrip/src/
//
// Editing this file will have NO effect on the preview or the
// published site. PRs that only touch src/ are incorrect.
// ============================================================

import { SITE_URL } from '@/lib/utils'

export default function robots() {
  return {
    rules: { userAgent: '*', allow: '/' },
    sitemap: `${SITE_URL}/sitemap.xml`,
  }
}
