// ============================================================
// DEPRECATED — DO NOT EDIT THIS FILE
// ============================================================
// This is the original Next.js source. It is NOT used by the
// live app. All changes must go to the Vite app instead:
//
//   artifacts/calculatetrip/src/
//
// Editing this file will have NO effect on the preview or the
// published site. PRs that only touch src/ are incorrect.
// ============================================================

import Link from 'next/link'

export default function Footer() {
  return (
    <footer className="bg-ocean-950 text-ocean-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 pt-16 pb-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10 mb-12">
          <div className="md:col-span-2">
            <p className="font-serif text-white text-2xl font-bold mb-3">CalculateTrip</p>
            <p className="text-sm leading-relaxed max-w-sm">
              Independent ratings across food, beach, pool, value, and service — so you can book your all-inclusive with confidence.
            </p>
          </div>

          <div>
            <p className="text-white font-semibold text-sm uppercase tracking-wider mb-4">Browse</p>
            <ul className="space-y-2.5 text-sm">
              {[
                { label: 'All Resorts', href: '/resorts/' },
                { label: 'Adults-Only', href: '/best-adults-only-all-inclusive-resorts/' },
                { label: 'Family Resorts', href: '/best-family-all-inclusive-resorts/' },
                { label: 'Best Value', href: '/best-value-all-inclusive-resorts/' },
                { label: 'Best Beach', href: '/best-beach-all-inclusive-resorts/' },
              ].map((l) => (
                <li key={l.href}>
                  <Link href={l.href} className="hover:text-white transition-colors">{l.label}</Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <p className="text-white font-semibold text-sm uppercase tracking-wider mb-4">Destinations</p>
            <ul className="space-y-2.5 text-sm">
              {[
                { label: 'Panama', href: '/destination/panama/' },
                { label: 'Belize', href: '/destination/belize/' },
                { label: 'Saint Lucia', href: '/destination/saint-lucia/' },
                { label: 'British Virgin Islands', href: '/destination/british-virgin-islands/' },
              ].map((l) => (
                <li key={l.href}>
                  <Link href={l.href} className="hover:text-white transition-colors">{l.label}</Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="border-t border-ocean-900 pt-8 text-xs text-ocean-500">
          Some links on this site are affiliate links. We may earn a commission at no extra cost to you. All ratings are independently researched.
        </div>
      </div>
    </footer>
  )
}
