// ============================================================
// DEPRECATED — DO NOT EDIT THIS FILE
// ============================================================
// This is the original Next.js source. It is NOT used by the
// live app. All changes must go to the Vite app instead:
//
//   artifacts/calculatetrip/src/
//
// Editing this file will have NO effect on the preview or the
// published site. PRs that only touch src/ are incorrect.
// ============================================================

export function scoreColor(s) {
  if (s === null) return 'text-gray-300'
  if (s >= 9.5) return 'text-emerald-600'
  if (s >= 9.0) return 'text-green-500'
  if (s >= 8.0) return 'text-amber-500'
  return 'text-orange-400'
}

export function scoreBg(s) {
  if (s === null) return 'bg-gray-200'
  if (s >= 9.5) return 'bg-emerald-500'
  if (s >= 9.0) return 'bg-green-400'
  if (s >= 8.0) return 'bg-amber-400'
  return 'bg-orange-400'
}

export function scoreLabel(s) {
  if (s === null) return 'N/A'
  if (s >= 9.5) return 'Exceptional'
  if (s >= 9.0) return 'Superb'
  if (s >= 8.0) return 'Excellent'
  if (s >= 7.0) return 'Good'
  return 'Fair'
}

export default function RatingBar({ label, score }) {
  if (score === null) return null
  return (
    <div className="flex items-center gap-4 group">
      <span className="text-sm text-ocean-700 w-36 shrink-0 font-sans">{label}</span>
      <div className="flex-1 bg-ocean-100 rounded-full h-1.5 overflow-hidden">
        <div
          className={`h-full rounded-full transition-all ${scoreBg(score)}`}
          style={{ width: `${(score / 10) * 100}%` }}
        />
      </div>
      <span className={`text-sm font-bold tabular-nums w-8 text-right font-sans ${scoreColor(score)}`}>
        {score}
      </span>
      <span className="text-xs text-ocean-400 w-20 hidden sm:block font-sans">{scoreLabel(score)}</span>
    </div>
  )
}
